// Mock data for Shop: products, categories, and projects

export const categories = [
  { id: "trending", name: "Trending" },
  { id: "new", name: "New" },
  { id: "sale", name: "Sale" },
  { id: "christmas", name: "Christmas" },
  { id: "summer", name: "Summer" },
];

export const projects = [
  { id: "p1", name: "Centro Comercial Colombo", budget: 40000, status: "in_progress" },
  { id: "p2", name: "Lisbon Municipality", budget: 25000, status: "created" },
  { id: "p3", name: "Luxury Hotel Chain", budget: 30000, status: "created" },
];

// Helper images from public/demo-images (fallback to unsplash if missing)
const img = (path, fallback) => path || fallback;
// Simple SVG color placeholder for temporary product images
const svg = (color) => `data:image/svg+xml;utf8,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='800' height='800'><rect width='100%' height='100%' fill='${color}'/></svg>`)}`;

export const products = [
  {
    id: "prd-001",
    name: "IPL317R",
    price: 1299,
    stock: 32,
    videoFile: "IPL317R.mp4",
    images: {
      day: img("/SHOP/TRENDING/DAY/IPL317R_DAY.png", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"),
      night: img("/SHOP/TRENDING/NIGHT/IPL317R_NIGHT.png", "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"),
      colors: {
        brancoPuro: img("/demo-images/decorations/star_white.jpg", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800"),
        vermelho: svg('#ef4444'),
      },
    },
    tags: ["trending", "christmas"],
    type: "2D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Poste",
    specs: {
      descricao: "Decorative banner-style light for pole mounting. Fictitious data for demo.",
      tecnicas: "230V AC, IP65, 48W",
      dimensoes: "2.80 m x 0.80 m",
      dimensions: { widthM: 0.80, heightM: 2.80 },
      weight: "11 kg",
      effects: "SLOWFLASH & SOFT XLED (Pure White and Red)",
      materiais: "LED modules, aluminum, white and red bioprint",
      stockPolicy: "Made to order (lead time 2–4 weeks)",
    },
  },
  {
    id: "prd-002",
    name: "Hanging Star 2D",
    price: 349,
    stock: 8,
    images: {
      day: img("/demo-images/decorations/star_day.jpg", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"),
      night: img("/demo-images/decorations/star_night.jpg", "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"),
      colors: {
        brancoPuro: img("/demo-images/decorations/star_white.jpg", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800"),
        brancoQuente: img("/demo-images/decorations/star_warm.jpg", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800"),
      },
    },
    tags: ["new", "christmas"],
    type: "2D",
    usage: "Shopping",
    location: "Interior",
    mount: "Transversal",
    specs: {
      descricao: "Lightweight star for indoor environments.",
      tecnicas: "IP20, 24V, 25W",
      dimensoes: "0.8m x 0.8m",
      materiais: "PVC, SMD LED",
    },
  },
  {
    id: "prd-003",
    name: "Pathway Light",
    price: 499,
    stock: 47,
    images: {
      day: img("/demo-images/decorations/path_day.jpg", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"),
      night: img("/demo-images/decorations/path_night.jpg", "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"),
      colors: {
        brancoPuro: img("/demo-images/decorations/star_white.jpg", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800"),
        brancoQuente: img("/demo-images/decorations/star_warm.jpg", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800"),
      },
    },
    tags: ["sale", "summer"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Chão",
    specs: {
      descricao: "Modular bollards for outdoor pathways.",
      tecnicas: "IP67, 24V, 12W",
      dimensoes: "0.6m x 0.15m",
      materiais: "Anodized aluminium",
    },
  },
  {
    id: "prd-004",
    name: "IPL337",
    price: 129,
    stock: 150,
    images: {
      day: img("/SHOP/TRENDING/DAY/IPL337.png", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"),
      night: img("/SHOP/TRENDING/NIGHT/IPL337.png", "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"),
      colors: {
        brancoPuro: img("/demo-images/decorations/star_white.jpg", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800"),
        brancoQuente: img("/demo-images/decorations/star_warm.jpg", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800"),
      },
    },
    tags: ["new", "summer"],
    type: "2D",
    usage: "Shopping",
    location: "Interior",
    mount: "Poste",
    specs: {
      descricao: "Flexible LED strip for a variety of applications.",
      tecnicas: "IP20, 12V, 14W/m",
      dimensoes: "5 m reel",
      materiais: "Flexible PCB, SMD LED",
    },
  },
  {
    id: "prd-005b",
    name: "GX350LW",
    price: 899,
    stock: 18,
    videoFile: "GX350LW.mp4",
    images: {
      day: img("/SHOP/TRENDING/DAY/GX350LW.png", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"),
      night: img("/SHOP/TRENDING/NIGHT/GX350LW_NIGHT.png", "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"),
      colors: {
        brancoPuro: img("/demo-images/decorations/star_white.jpg", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800"),
        brancoQuente: img("/demo-images/decorations/star_warm.jpg", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800"),
      },
    },
    tags: ["trending"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Chão",
    specs: {
      descricao: "SCENETTE JOSÉ",
      tecnicas: "IP65, 230V AC, 85W",
      dimensoes: "2.4 m (H) x 2.0 m (W) x 0.5 m (D)",
      dimensions: { widthM: 2.0, heightM: 2.4, depthM: 0.5 },
      weight: "36 kg",
      effects: "Warm white & Pure white XLED (257)",
      materiais: "Warm‑white and pure‑white LEDs, aluminum",
    },
  },
  {
    id: "prd-005",
    name: "GX349L",
    price: 899,
    stock: 21,
    videoFile: "GX349L.mp4",
    images: {
      day: img("/SHOP/TRENDING/DAY/GX349L_DAY.png", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"),
      night: img("/SHOP/TRENDING/NIGHT/GX349L_NIGHT.png", "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"),
      colors: {
        brancoPuro: img("/demo-images/decorations/star_white.jpg", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800"),
        brancoQuente: img("/demo-images/decorations/star_warm.jpg", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800"),
      },
    },
    tags: ["trending", "sale"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Chão",
    specs: {
      descricao: "Luminous 3D bear-shaped sculpture with illuminated decorative swirl.",
      tecnicas: "IP65, 230V AC, 60W, high‑efficiency LEDs",
      dimensoes: "2.60 m (W) x 1.50 m (H) x 1.10 m (D)",
      dimensions: { widthM: 2.60, heightM: 1.50, depthM: 1.10 },
      materiais: "White bioprint, gold bioprint, Fil Lumière, pure white LEDs with flash",
      weight: "65 kg",
      effects: "Pure white with warm‑white accent (day/night modes)",
    },
  },
  {
    id: "prd-005a",
    name: "IPL337W",
    price: 1299,
    stock: 28,
    videoFile: "IPL337W.mp4",
    images: {
      day: img("/SHOP/TRENDING/DAY/IPL337W.png", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"),
      night: img("/SHOP/TRENDING/NIGHT/IPL337W.png", "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"),
      colors: { brancoQuente: img("/demo-images/decorations/star_warm.jpg", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800") },
    },
    tags: ["trending"],
    type: "2D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Poste",
    variantProductByColor: { brancoPuro: "prd-006", brancoQuente: "prd-005a" },
    specs: {
      descricao: "GATSBY BANNER",
      tecnicas: "230V AC, IP65, 50W",
      dimensoes: "2.80 m x 0.80 m",
      dimensions: { widthM: 0.80, heightM: 2.80 },
      weight: "8 kg",
      effects: "SLOWFLASH & SOFT XLED",
      materiais: "Warm‑white LEDs with flash, gold bioprint, aluminum, Comet wire",
      stockPolicy: "Made to order (lead time 2–4 weeks)",
    },
  },
  // Additional placeholder products to reach 16 items for the grid
  {
    id: "prd-006",
    name: "IPL337",
    price: 1299,
    stock: 31,
    videoFile: "IPL337.mp4",
    images: {
      day: img("/SHOP/TRENDING/DAY/IPL337.png", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"),
      night: img("/SHOP/TRENDING/NIGHT/IPL337.png", "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800"),
      colors: { brancoPuro: img("/demo-images/decorations/star_white.jpg", "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800") }
    },
    tags: ["trending", "summer"],
    type: "2D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Poste",
    variantProductByColor: { brancoPuro: "prd-006", brancoQuente: "prd-005a" },
    specs: {
      descricao: "GATSBY BANNER",
      tecnicas: "230V AC, IP65, 50W",
      dimensoes: "2.80 m x 0.80 m",
      dimensions: { widthM: 0.80, heightM: 2.80 },
      weight: "8 kg",
      effects: "SLOWFLASH & SOFT XLED",
      materiais: "Pure‑white LEDs with flash, white bioprint, aluminum, Comet wire",
      stockPolicy: "Made to order (lead time 2–4 weeks)",
    },
  },
  {
    id: "prd-007",
    name: "Star Burst 3D",
    price: 749,
    oldPrice: 899,
    stock: 5,
    images: { day: svg('#f97316'), night: svg('#9a3412'), colors: { brancoPuro: svg('#fde68a') } },
    tags: ["trending", "christmas"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Poste",
  },
  {
    id: "prd-008",
    name: "Aurora Panel",
    price: 560,
    stock: 73,
    images: { day: svg('#14b8a6'), night: svg('#0f766e'), colors: { verde: svg('#10b981'), azul: svg('#3b82f6') } },
    tags: ["trending"],
    type: "2D",
    usage: "Shopping",
    location: "Interior",
    mount: "Transversal",
  },
  {
    id: "prd-009",
    name: "Neon Arch",
    price: 420,
    stock: 0,
    images: { day: svg('#a78bfa'), night: svg('#6d28d9'), colors: { brancoQuente: svg('#fbbf24') } },
    tags: ["trending", "sale"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Poste",
  },
  {
    id: "prd-010",
    name: "Snowflake 2D",
    price: 299,
    stock: 95,
    images: { day: svg('#e5e7eb'), night: svg('#9ca3af'), colors: { brancoPuro: svg('#ffffff') } },
    tags: ["trending", "christmas"],
    type: "2D",
    usage: "Shopping",
    location: "Interior",
    mount: "Transversal",
  },
  {
    id: "prd-011",
    name: "Path Light Mini",
    price: 189,
    stock: 33,
    images: { day: svg('#22c55e'), night: svg('#166534'), colors: { verde: svg('#16a34a') } },
    tags: ["trending", "summer"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Chão",
  },
  {
    id: "prd-012",
    name: "Glow Sphere",
    price: 379,
    stock: 18,
    images: { day: svg('#f43f5e'), night: svg('#9f1239'), colors: { vermelho: svg('#ef4444') } },
    tags: ["trending"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Chão",
  },
  {
    id: "prd-013",
    name: "Icicle String",
    price: 149,
    stock: 120,
    images: { day: svg('#93c5fd'), night: svg('#1d4ed8'), colors: { azul: svg('#60a5fa') } },
    tags: ["trending", "sale"],
    type: "2D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Transversal",
  },
  {
    id: "prd-014",
    name: "Candy Cane Duo",
    price: 259,
    stock: 9,
    images: { day: svg('#ef4444'), night: svg('#991b1b'), colors: { vermelho: svg('#f87171'), brancoPuro: svg('#ffffff') } },
    tags: ["trending", "christmas"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Poste",
  },
  {
    id: "prd-015",
    name: "Meteor Shower",
    price: 329,
    stock: 44,
    images: { day: svg('#f59e0b'), night: svg('#b45309'), colors: { brancoQuente: svg('#fbbf24') } },
    tags: ["trending"],
    type: "2D",
    usage: "Shopping",
    location: "Interior",
    mount: "Transversal",
  },
  {
    id: "prd-016",
    name: "Polar Star 3D",
    price: 999,
    oldPrice: 1199,
    stock: 6,
    images: { day: svg('#0ea5e9'), night: svg('#1e3a8a'), colors: { brancoPuro: svg('#e2e8f0') } },
    tags: ["trending", "sale"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Poste",
  },
  {
    id: "prd-017",
    name: "Twinkle Net",
    price: 210,
    stock: 88,
    images: { day: svg('#ffe4e6'), night: svg('#fb7185'), colors: { brancoPuro: svg('#fafafa') } },
    tags: ["trending"],
    type: "2D",
    usage: "Shopping",
    location: "Interior",
    mount: "Transversal",
  },
  {
    id: "prd-018",
    name: "Crystal Drop",
    price: 640,
    stock: 27,
    images: { day: svg('#d1fae5'), night: svg('#34d399'), colors: { verde: svg('#10b981') } },
    tags: ["trending"],
    type: "3D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Poste",
  },
  {
    id: "prd-019",
    name: "Comet Trail",
    price: 285,
    stock: 52,
    images: { day: svg('#ede9fe'), night: svg('#a78bfa'), colors: { azul: svg('#60a5fa'), brancoQuente: svg('#facc15') } },
    tags: ["trending"],
    type: "2D",
    usage: "Shopping",
    location: "Exterior",
    mount: "Transversal",
  },
];

export function getProductsByCategory(categoryId) {
  if (!categoryId) return products;
  return products.filter((p) => p.tags.includes(categoryId));
}


