version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: instructions_demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

